### ISSUE TITLE
Inconsistent save behavior when closing properties

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/pipeline-editor#118]
Whether or not changes to properties are saved depends on how it is closed. If a user clicks away, leaving the panel open, the changes are saved. When a user closes the panel using the button changes are not saved. The save behavior should be the same no matter how properties is closed.

**Comment by bourdakos1** [comment]
Is this in the latest version? This was an issue a while ago, but should be fixed. Properties are saved anytime a value changes, not when changing focus

**Comment by ajbozarth** [comment]
I noticed it when working on #116 and thought it was just my code, but the behavior is the same when editing the CPU value as well

**Comment by bourdakos1** [comment]
Oh yea I see, I think it's persisting the value, but there is a bug when the panel disappears and reappears and it doesn't realize the value changed. Here's a video, notice the actual file updates with the correct value:

![video](https://thumbs.gfycat.com/SleepySeveralGoldfinch-size_restricted.gif)

**Comment by ajbozarth** [comment]
yep, that's the behavior, and my changes are consistent with it as well. We should leave this open to deal with that bug though, feel free to update the title and description if you want to.

**Comment by bourdakos1** [comment]
this should be fixed with #122

**Comment by bourdakos1** [comment]
I believe this has been fixed, closing
