### ISSUE TITLE
File based nodes thoughts

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/pipeline-editor#34]
- We should validate that the file exists, how often? Do we need to watch the file somehow?
- Should we change the file label to just be the basename? `xxx.ipynb` feels a bit noisy...
- If a file is renamed should the node's file path also be updated?

**Comment by lresende** [comment]
> > * We should validate that the file exists, how often? Do we need to watch the file somehow?
> 
> I would think when opening the file and on running / exporting? Also saving? I think that'd be enough

So, this should be part of the pipeline validation logic, so, whenever the validation occours.

**Comment by bourdakos1** [comment]
Yea, I was assuming during validation was the bare minimum. I was more wondering if we should do any file watching for when required files are renamed/moved
