### ISSUE TITLE
Update StringArrayControl to handle plain lists

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/pipeline-editor#38]
Currently, string array properties in a pipeline file are just a plain array of strings. However, we need stable IDs for our string/file array form control to safely render/edit values. This is a breaking change, so we need to increment the current pipeline version from `3` to `4`.

**Comment by lresende** [comment]
Could you give an example?

**Comment by bourdakos1** [comment]
@lresende An example of what?

**Comment by bourdakos1** [comment]
as per discussion, we won't be adding IDs to list items. Instead we will need to update StringArrayControl to handle plain lists
